# Generated by Django 5.0.1 on 2025-11-21 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='collections/', verbose_name='Image')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['collection__order', 'order', 'name'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='products_ca_collect_278fba_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='collection_type',
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['slug'], name='products_co_slug_c9aad1_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['order'], name='products_co_order_af0ba3_idx'),
        ),
        migrations.AddField(
            model_name='category',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.collection', verbose_name='Collection'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['collection'], name='products_ca_collect_50f7e8_idx'),
        ),
    ]
