# Generated by Django 5.0.1 on 2025-11-21 10:27

from django.db import migrations


def create_collections_and_link_categories(apps, schema_editor):
    """
    Crée les 4 collections et associe les catégories existantes
    """
    Collection = apps.get_model('products', 'Collection')
    Category = apps.get_model('products', 'Category')
    
    # Créer les 4 collections
    collections_data = [
        {'name': 'Hommes', 'slug': 'men', 'description': 'Collection masculine traditionnelle', 'order': 1},
        {'name': 'Femmes', 'slug': 'women', 'description': 'Collection féminine élégante', 'order': 2},
        {'name': 'Babouches', 'slug': 'babouches', 'description': 'Babouches traditionnelles en cuir', 'order': 3},
        {'name': 'Lins', 'slug': 'lins', 'description': 'Collection en lin léger', 'order': 4},
    ]
    
    collections = {}
    for data in collections_data:
        collection, created = Collection.objects.get_or_create(
            slug=data['slug'],
            defaults={
                'name': data['name'],
                'description': data['description'],
                'order': data['order']
            }
        )
        collections[data['slug']] = collection
    
    # Mapping des catégories vers les collections
    # Note: Ce mapping se base sur les slugs de catégories créés par populate_products
    category_to_collection = {
        # Hommes
        'boubous': 'men',
        'gandouras': 'men',
        'costumes': 'men',
        'chemises': 'men',
        'pantalons': 'men',
        # Femmes
        'robes': 'women',
        'ensembles': 'women',
        'sacs': 'women',
        # Babouches
        'babouches-cuir': 'babouches',
        'babouches-brodees': 'babouches',
        # Lins
        'chemises-lin': 'lins',
        'pantalons-lin': 'lins',
    }
    
    # Associer chaque catégorie à sa collection
    for category_slug, collection_slug in category_to_collection.items():
        try:
            category = Category.objects.get(slug=category_slug)
            category.collection = collections[collection_slug]
            category.save()
        except Category.DoesNotExist:
            # La catégorie n'existe pas encore (cas où on n'a pas encore run populate_products)
            pass


def reverse_migration(apps, schema_editor):
    """
    Nettoie les collections créées
    """
    Collection = apps.get_model('products', 'Collection')
    Collection.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_collection_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_collections_and_link_categories, reverse_migration),
    ]
