# Generated by Django 5.0.1 on 2025-11-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_populate_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='sleeve_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type de manche'),
        ),
    ]
