# Generated by Django 5.0.1 on 2025-11-21 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariant_sleeve_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Attribut',
                'verbose_name_plural': 'Attributs',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product', 'sku'], 'verbose_name': 'Variante de produit', 'verbose_name_plural': 'Variantes de produits'},
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Taille'),
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Valeur')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.attribute', verbose_name='Attribut')),
            ],
            options={
                'verbose_name': "Valeur d'attribut",
                'verbose_name_plural': "Valeurs d'attributs",
                'ordering': ['attribute', 'value'],
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='variants', to='products.attributevalue', verbose_name='Attributs'),
        ),
    ]
