# Generated by Django 5.0.1 on 2025-11-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_attribute_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sleeve_type',
        ),
    ]
